name: CI/CD Pipeline

# когда запускать
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# переменная, чтобы не повторять текст
env:
  PATH_FOR_LINT: "src config tests"

# какие джобы
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: # шаги джобы
      - name: Checkout code         # копируем код
        uses: actions/checkout@v2   # используем готовый action

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          source .bashrc
          pip install --upgrade pip
          pip install -r requirements/requirements-lint.txt
          pip install -r requirements/requirements.txt

      - name: Run linters
        run: isort ${PATH_FOR_LINT} --check --profile black

      - name: Run black
        run: black ${PATH_FOR_LINT} --check

      - name: Run ruff
        run: ruff check ${PATH_FOR_LINT}

  # test:
  # build:
  # deploy:
